---
title: "SOLR Analysis"
author: "Daniel Fireman (danielfireman@gmail.com)"
date: "February 20, 2017"
output: pdf_document
---


```{r setup_results, include=FALSE}
knitr::opts_knit$set(kable.force.latex = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.align = "center")
knitr::opts_chunk$set(fig.asp = 0.32)

require(ggplot2)
require(dplyr)

COLOR_BLIND_PALETTE <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
CINT_SECS <- 2
START_OFFSET <- 180/CINT_SECS
END_OFFSET <- 60/CINT_SECS
EXP_ID <- "nogci_optgc_poisson_1"
CHART_TEXT_SIZE <- 7
LEGEND_TEXT_SIZE <- 5

get_fname <- function(f) {
  return(paste("results/", f, "_", EXP_ID, ".csv", sep=""))
}
```

```{r}
print(paste("Experiment ID:", EXP_ID))
```

```{r}
tp <- read.csv(get_fname("tp.200"))
tp <- tp[(START_OFFSET+1):(nrow(tp)-END_OFFSET),]
tp["tsrange"] <- c(NA, (tp$ts[2:nrow(tp)] - tp$ts[1:(nrow(tp)-1)])/1000)
tp["value"] <- c(NA, tp$count[2:nrow(tp)] / tp$tsrange[2:nrow(tp)])

plotThroughput <- function(df) {
  startTime <- df$ts[1]-(df$ts[2]-df$ts[1])
  print(
    ggplot(df, size = 1, aes(x = (ts-startTime)/1000, y = value)) +
      geom_line() +
      ylab("Throughput (Req/Sec)") +
      xlab("Time (s)") +
      scale_color_manual(values = COLOR_BLIND_PALETTE) +
      scale_y_continuous(limits = c(0, 100)) +
      theme(
        legend.title=element_blank(),
        legend.position = c(0.1, 0.9),
        text = element_text(size=CHART_TEXT_SIZE),
        axis.text = element_text(size = CHART_TEXT_SIZE))
  )
}

plotThroughput(tp[2:nrow(tp),])  # Ignoring first line.
```

```{r}
latency <- read.csv(get_fname("latency.200"))
colnames(latency) <- c("ts", "p50", "p90", "p99", "p999")
latency <- latency %>% filter(p999 > 0 & p90 > 0 & p99 > 0)  # Getting rid of noise.
latency <- latency[(START_OFFSET + 1):(nrow(latency) - END_OFFSET),]

plotLatency <- function(df) {
  startTime <- df$ts[1]-(df$ts[2]-df$ts[1])
  print(
    ggplot(df, size = 1) +
      geom_line(aes(x = (ts-startTime)/1000, y = p50, color = "50")) +
      geom_line(aes(x = (ts-startTime)/1000, y = p90, color = "90")) +
      geom_line(aes(x = (ts-startTime)/1000, y = p99, color = "99")) +
      geom_line(aes(x = (ts-startTime)/1000, y = p999, color = "999")) +
      ylab("Latency (ms)") +
      xlab("Time (s)") +
      scale_color_manual(values = COLOR_BLIND_PALETTE) +
      theme(
        legend.title=element_blank(),
        legend.position="top", #legend.position = c(0.96, 0.87),
        legend.text=element_text(size=LEGEND_TEXT_SIZE),
        text = element_text(size=CHART_TEXT_SIZE),
        axis.text = element_text(size = CHART_TEXT_SIZE))
  )
}
plotLatency(latency)
```

```{r}
gc <- read.csv(get_fname("gc"))
gc <- gc[(START_OFFSET + 1):(nrow(gc) - END_OFFSET),]
gc["young.time.value"] <- c(NA, (gc$young.time[2:nrow(gc)] - gc$young.time[1:(nrow(gc)-1)]))
gc["old.time.value"] <- c(NA, (gc$old.time[2:nrow(gc)] - gc$old.time[1:(nrow(gc)-1)]))
plotGC <- function(df) {
  startTime <- df$ts[1]-(df$ts[2]-df$ts[1])
  print(
    ggplot(df, size = 1) +
      geom_line(aes(x = (ts-startTime)/1000, y = old.time.value, color = "Tenured")) +
      geom_line(aes(x = (ts-startTime)/1000, y = young.time.value, color = "Young")) +
      ylab("GC activity time (ms)") +
      xlab("Time (s)") +
      scale_color_manual(values = COLOR_BLIND_PALETTE) +
      scale_y_continuous(limits = c(0, 50)) +
      theme(
        legend.title=element_blank(),
        legend.position = "top", #legend.position = c(0.95, 0.95),
        text = element_text(size=CHART_TEXT_SIZE),
        axis.text = element_text(size = CHART_TEXT_SIZE))
  )
}
plotGC(gc[2:nrow(gc),])
```

```{r}
mem.pools <- read.csv(get_fname("mem.pools"))
mem.pools <- mem.pools[(START_OFFSET + 1):(nrow(mem.pools) - END_OFFSET),]

plotMemPools <- function(mem.pools) {
  startTime <- mem.pools$ts[1]
  print(ggplot(mem.pools) +
          geom_line(aes(x = (ts-startTime)/1000, y = old.used/1000000, color="Tenured")) +
          geom_line(aes(x = (ts-startTime)/1000, y = young.used/1000000, color="Eden")) +
          geom_line(aes(x = (ts-startTime)/1000, y = survivor.used/1000000, color="Survivor")) +
          ylab("Used Memory (MB)") +
          xlab("Time (s)") +
          scale_color_manual(values = COLOR_BLIND_PALETTE) +
          theme(
            legend.title=element_blank(),
            legend.position = "top", #legend.position = c(0.95, 0.95),
            text = element_text(size=CHART_TEXT_SIZE),
            axis.text = element_text(size = CHART_TEXT_SIZE)))
}
plotMemPools(mem.pools)
```
```{r}
cpu <- read.csv(get_fname("cpu"))
cpu <- cpu[(START_OFFSET+1):(nrow(cpu)-END_OFFSET),]

plotCPU <- function(df) {
  startTime <- df$ts[1]-(df$ts[2]-df$ts[1])
  print(
    ggplot(df, size = 1, aes(x = (ts-startTime)/1000, y = percent)) +
      geom_line() +
      ylab("Average CPU Usage (%)") +
      xlab("Time (s)") +
      scale_color_manual(values = COLOR_BLIND_PALETTE) +
      scale_y_continuous(limits = c(0, 100)) +
      theme(
        legend.title=element_blank(),
        legend.position = c(0.1, 0.9),
        text = element_text(size=CHART_TEXT_SIZE),
        axis.text = element_text(size = CHART_TEXT_SIZE))
  )
}

plotCPU(cpu)
```

