---
output:
  pdf_document: default
  html_document: default
---

```{r setup_results, include=FALSE}
knitr::opts_knit$set(kable.force.latex = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.align = "center")

require(ggplot4)
require(dplyr)
require(resample)
require(cowplot)
require(gridExtra)
require(xtable)
```

```{r message=FALSE, results='hide', warning=FALSE}
source("functions.R")
```

```{r datasets}
# Constants
COLOR_BLIND_PALETTE <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

NCORES <- 2
ID <- 1

# Threads
threads <- threadData(NCORES, ID)

# CPU
gc_cpu <- getGcCpuData(NCORES, ID)

t <- read.csv("../data/2cores/server/responses.200.csv")  %>% filter(t >= min(gc_cpu$t) & t <= max(gc_cpu$t))
req <- read.csv("../data/2cores/server/request.csv")  %>% filter(t >= min(gc_cpu$t) & t <= max(gc_cpu$t))
```
# 2 Cores

```{r fig.align="center", fig.pos="h", fig.height=2, fig.width=3.5}
ggplot(size = 1) +
  geom_line(data = gc_cpu, aes(x = t/ 1000, y = (gc.time.sum/cpu.time) * 100, color = "Prop")) +
  ylab("GC / Total CPU time (%)") +
  xlab("Time (s)") +
  scale_color_manual(values = COLOR_BLIND_PALETTE) +
  theme(
    legend.title=element_blank(),
    legend.position = c(0.1, 0.9),
    text = element_text(size=8),
    axis.text = element_text(size = 8))
```
```{r fig.align="center", fig.pos="h", fig.height=2, fig.width=3.5}
ggplot(size = 1) +
  geom_line(data = gc_cpu, aes(x = t/ 1000, y = cpu.load)) +
  ylab("CPU Load (%)") +
  xlab("Time (s)") +
  scale_color_manual(values = COLOR_BLIND_PALETTE) +
  theme(
    legend.title=element_blank(),
    legend.position = c(0.1, 0.9),
    text = element_text(size=8),
    axis.text = element_text(size = 8))
```

```{r fig.align="center", fig.pos="h", fig.height=2, fig.width=3.5}
ggplot(size = 1) +
  geom_line(data = gc_cpu, aes(x = t/ 1000, y = gc.minor.time / 1000, color = "Minor GC")) +
  geom_line(data = gc_cpu, aes(x = t/ 1000, y = gc.full.time / 1000, color = "Full GC")) +
  ylab("CPU Time Spent in GC (s)") +
  xlab("Time (s)") +
  scale_color_manual(values = COLOR_BLIND_PALETTE) +
  theme(
    legend.title=element_blank(),
    legend.position = c(0.12, 0.9),
    text = element_text(size=8),
    axis.text = element_text(size = 8))
```


```{r fig.align="center", fig.pos="h", fig.height=2, fig.width=3.5}
plotThroughput(t)
```
```{r fig.align="center", fig.pos="h", fig.height=2, fig.width=3.5}
plotResponseTime(req)
```

# Threads

```{r fig.align="center", fig.pos="h", fig.height=2, fig.width=3.5}
plotThreads(threads)
```

# Memory

```{r memData, cache=TRUE}
mem.heap <- memData(NCORES, ID, "heap")
mem.nonheap <- memData(NCORES, ID, "non-heap")
mem.total <- memData(NCORES, ID, "total")
mem.compressedClass <- memData(NCORES, ID, "pools.Compressed-Class-Space")
mem.codeCache <- memData(NCORES, ID, "pools.Code-Cache")
mem.metaspace <- memData(NCORES, ID, "pools.Metaspace")
mem.oldGen <- memData(NCORES, ID, "pools.PS-Old-Gen")
mem.eden <- memData(NCORES, ID, "pools.PS-Eden-Space")
mem.survivor <- memData(NCORES, ID, "pools.PS-Survivor-Space")
```

```{r fig.align="center", fig.pos="h", fig.height=2, fig.width=3.5}
plotMem(mem.heap, "Heap (MB)")
plotMem(mem.total, "Total Memory (MB)")
plotMem(mem.nonheap, "Non-Heap (MB)")
```

## Pools

```{r fig.align="center", fig.pos="h", fig.height=2, fig.width=3.5}
plotMem(mem.oldGen, "Old Generation (MB)")
plotMem(mem.eden, "Eden (MB)")
plotMem(mem.survivor, "Survivor (MB)")
plotMem(mem.metaspace, "Metaspace (MB)")
plotMem(mem.codeCache, "Code Cache (MB)")
plotMem(mem.compressedClass, "Compressed Classes (MB)")
```

# Predictor

```{r, echo=F}
lm.df <- merge(select(req, t, mean), select(mem.total, t, used), by = "t")
colnames(lm.df) <- c("t", "response.time", "mem.used")
lm.df <- merge(lm.df, gc_cpu, by = "t")
lm.df <- merge(lm.df, threads , by = "t")
model <- lm(
  response.time ~ (mem.used * prop.cpu.gc) + prop.threads.runnable + cpu.load,
  data = lm.df)
summary(model)
```