# Metodologia de pesquisa e estratégia de ação {#sec:metodpesq}

## Metodologia {#sec:metod}

Esta seção apresenta um detalhamento da metodologia utilização para execução
desse plano de trabalho. A metodologia de pesquisa será predominantemente empírica,
porém este não será o único método. Dois métodos principais de pesquisa
científica serão combinados: pesquisa sistemática e pesquisa quantitativa.

A pesquisa sistemática de temas relacionados servirá  para identificar com
clareza o estado-da-arte nas diversas áreas de pesquisa relacionadas com o
tema em estudo.

A pesquisa empírica quantitativa tem como principal objetivo avaliar os
benefícios dos mecanismos propostos em cenários reais, ou próximos do real.
Pretende-se usar duas técnicas de avaliação: avaliação baseada em experimentos
de simulação e avaliação baseada em experimentos de medição. Os simuladores
serão utilizados para implementação de modelos e sua validação será feita com a
realização de experimentos de medição executados em um ambiente real. Além
disso, todo o software desenvolvido será verificado com testes de unidade,
integração e testes de sistema, bem como testes de carga e de regressão.

## Estratégia de ação para execução do plano {#sec:estrategia}

Visando atingir as metas propostas, o plano de trabalho será executado em três
duas principais, cobrindo cada um dos temas discutidos anteriormente:

1. desenvolvimento de mecanismos para diminuição do impacto negativo da um
*runtime* na utilização de CPU e memória RAM;

1. desenvolvimento de um serviço para auxilio à configuração de *runtimes*
baseado nas características de execução das aplicações e da carga aplicada;

1. generalização/adaptação dos mecanismos citados acima para *runtimes* das
linguagens mais utilizadas no cenário global;

1. adaptação do mecanismo para gerência semi-automática online (reconfiguração)

Cada uma dessas fases seguirá o mesmo conjunto de etapas descritas a seguir:

**Etapa 1: revisão bibliográfica**

Nesta etapa será realizada uma extensa revisão bibliográfica, com o intuito de
identificar os trabalhos relacionados, as soluções propostas na literatura e
possíveis ideias para a solução dos problemas específicos da fase
correspondente.

**Etapa 2: formalização do problema**

Ao final desta etapa será produzida uma formalização do problema estudado e a
especificação clara dos requisitos que uma solução para o mesmo deve atender.

**Etapa 3: estudo e modelagem da proposta de solução**

Esta etapa compreende a modelagem do sistema estudado, a partir da formalização
realizada na etapa anterior. Ao final desta etapa, serão identificadas uma ou
mais abordagens para solucionar os problemas estudados.

**Etapa 4: avaliação da solução proposta escolhida**

A eficiência das abordagens selecionadas será avaliada através da análise de
modelos analíticos e/ou resultados de simulação. Esta etapa envolve o
planejamento e a execução dos experimentos de simulação, a definição dos
parâmetros de entrada e das métricas de desempenho que serão coletadas.

**Etapa 5: implementação e validação**

Nessa etapa as abordagens mais promissoras serão implementadas e o software
gerado será usado para executar experimentos em um sistema real que servirão
para validar os modelos analíticos e/ou os resultados de simulação.

**Etapa 6: escrita de artigos e relatórios**

Além das etapas descritas anteriormente, ao longo do desenvolvimento de todo o
trabalho de pesquisa serão gerados artigos científicos e relatórios de
progresso.